package:
  name: bellmans-gapc
  version: 2020.01.08

source:
  url: https://github.com/jlab/gapc/archive/2020.01.08.tar.gz
  sha256: 83ade6148d604d56df0e3fc7af5fba894328dcc6f64d6f7254e89d2f0698998b

build:
  number: 0
  skip: True # [osx]

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - flex
    - bison
    - boost
    - gsl
    - openblas
  run:
    - boost
    - gsl
    - openblas

test:
  files:
    # copy of file in upstream repo: testdata/grammar/nussinov.gap
    - nussinov.gap
  commands:
    # basic test if binary is executable
    - gapc -h
    # works for "normal" build, but I don't know how to copy the nussinov.gap file into the mulled build system
    # actually compile an instance from bgap source ...
    #- gapc -p 'bpmax2 * pretty' nussinov.gap
    # ... compile the generated C++ code ...
    #- make -f out.mf
    # ... and execute the resulting binary
    #- ./out ACUGAC

about:
  home: https://bibiserv.cebitec.uni-bielefeld.de/gapc
  license: 'GPLv3+'
  license_file: LICENSE
  summary: 'A language and compiler for algebraic dynamic programming.'
