package:
  name: bellmans-gapc
  version: 2020.01.08

source:
  url: https://github.com/jlab/gapc/archive/2020.01.08.tar.gz
  sha256: 83ade6148d604d56df0e3fc7af5fba894328dcc6f64d6f7254e89d2f0698998b

build:
  number: 0
  skip: True # [osx]

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - flex
    - bison
    - boost
    - gsl
    - openblas
  run:
    - boost
    - gsl
    - openblas

test:
  commands:
    - gapc -h #&> /dev/null
    - cp testdata/grammar/nussinov.gap .
    - gapc -p 'bpmax2 * pretty' nussinov.gap
    - make -f out.mf
    - ./out ACUGAC

about:
  home: https://bibiserv.cebitec.uni-bielefeld.de/gapc
  license: 'GPLv3+'
  license_file: LICENSE
  summary: 'A language and compiler for algebraic dynamic programming.'
