{% set name = "pbipa" %}
{% set version = "1.0.4" %}
{% set sha256 = "b1bb63370cecfac6c7a85563afd6c0d9dbe344a2ca434331ec7f63e158a4969f" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://github.com/PacificBiosciences/pbipa/releases/download/v{{ version }}/pbipa.tar.gz
    sha256: {{ sha256 }}

build:
  number: 0
  skip: True # [osx]

extra:
  recipe-maintainers:
    - pb-cdunn

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - zlib
    - htslib 1.9*
    - pcre
  run:
    - htslib 1.9*
    - networkx
    - snakemake-minimal
    - racon
    - pbmm2 # needs htslib < 1.10
    - nim-falcon
    - samtools

test:
  commands:
      - nighthawk --version
      - pblayout --version
      - pancake --version
      - ipa --help
      - ipa validate

about:
  home: 'https://github.com/PacificBiosciences/pbbioconda'
  license: "BSD 3-Clause Clear License"
  summary: "Improved Phased Assembly"
  authors:
    - isovic
    - zkronenberg
    - pb-cdunn
