{% set version = "1.4.2" %}

package:
  name: tidehunter
  version: {{ version }}

source:
  url: https://github.com/yangao07/TideHunter/releases/download/v{{ version }}/TideHunter-v{{ version }}.tar.gz
  sha256: 7654f879970a154ab595f87583eb72f8140f1bd0978258f4ab7e9afb4af24651

build:
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
  host:
    - zlib

test:
  commands:
    - TideHunter --version | grep {{ version }}

about:
  home: https://github.com/yangao07/TideHunter
  license: MIT
  license_file: LICENSE
  summary: 'TideHunter: efficient and sensitive tandem repeat detection from noisy long reads using seed-and-chain'
