{% set version = "0.12.4" %}

package:
  name: metalign
  version: {{ version }}

source:
  url: https://github.com/nlapier2/Metalign/archive/v{{ version }}.tar.gz
  sha256: 61f84c4dee8f03df7311316be1d4859dec41b2c12c5f4064efc354c58cbefdfd 

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python >=3.5
    - pip
    - setuptools >=24.2.0

  run:
    - python
    - cmash >=0.4.0
    - kmc
    - minimap2

test:

  commands:
    - metalign.py -h
    - select_db.py -h
    - map_and_profile.py -h

about:
  home: https://github.com/nlapier2/Metalign
  summary: 'Metalign: efficient alignment-based metagenomic profiling via containment min hash'
  license: MIT
  license_family: MIT
  license_file: LICENSE
  dev_url: https://github.com/nlapier2/Metalign
  doc_url: https://github.com/nlapier2/Metalign

extra:
  identifiers:
    - doi:10.1101/2020.01.17.910521
  recipe-maintainers:
    - nlapier2
    - dkoslicki
  authors:
    - nlapier2
    - mealser
    - eeskin
    - dkoslicki
    - smangul1
